id: I36A73E1C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T12:34:37+00:00'
last_modified: '2022-06-09T05:05:05.795489+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22014
  title: གླིང་རྗེ་གེ་སར་རྒྱལ་པོའི་སྒྲུང་དམྱལ་གླིང་རྫོགས་པ་ཆེན་པོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BCC6:
      image_group_id: I4224
      title: ''
      total_pages: 388
      order: 1
      base_file: BCC6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
