id: P008184
initial_creation_type: ocr
source_metadata:
  id: bdr:W22014
  title: གླིང་རྗེ་གེ་སར་རྒྱལ་པོའི་སྒྲུང་དམྱལ་གླིང་རྫོགས་པ་ཆེན་པོ
  author: ''
  volumes:
    b8cafd5ee84c423abe3c233874082d39:
      image_group_id: I4224
      title: ''
      volume_number: 1
      total_pages: 388
      base_file: v001.txt
