id: P008184
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W22014
  title: གླིང་རྗེ་གེ་སར་རྒྱལ་པོའི་སྒྲུང་དམྱལ་གླིང་རྫོགས་པ་ཆེན་པོ
  author: ''
  volumes:
    b8cafd5ee84c423abe3c233874082d39:
      image_group_id: I4224
      title: ''
      volume_number: 1
      total_pages: 388
      base_file: v001.txt
